
#before while loop:
input_left_start=False
inputnum=0
i=0
#if 'limited input left' power-up is generated by the random generator, a changes into True(written in random function)
input_left_start=True
if i==0 and input_left_start:
    input_total=(numbombs-correct_bombs)*2
    i=1
#ensure that the value of input_total doesn't change
inputleft=input_total-inputnum
#before printing output
if input_left_start:
    if inputleft==0:
        print(colors.num6+"YOU LOSE HAHAHAHAHAHHAHA LMAO😊😊😊!!"+colors.return_color)
        time.sleep(2)#To allow the player to react that he has lost
        printout(board)
        safe=False
        break

if input_left_start:
    print('Input left: ',inputleft)#after printing Bombs and before displaying Modes

if input_left_start:
    inputnum+=1 #after input




